name: zappay-backend
services:
- name: api
  source_dir: /backend
  github:
    repo: vaing85/zappay-app
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3001
  health_check:
    http_path: /health
    initial_delay_seconds: 10
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "3001"
  - key: JWT_SECRET
    value: ${JWT_SECRET}
  - key: REFRESH_TOKEN_SECRET
    value: ${REFRESH_TOKEN_SECRET}
  - key: DB_URL
    value: ${zappay-postgres.DATABASE_URL}
  - key: REDIS_URL
    value: ${zappay-redis.REDIS_URL}
  # Rapyd Payment Configuration
  - key: RAPYD_ACCESS_KEY
    value: ${RAPYD_ACCESS_KEY}
  - key: RAPYD_SECRET_KEY
    value: ${RAPYD_SECRET_KEY}
  - key: RAPYD_BASE_URL
    value: https://sandboxapi.rapyd.net
  - key: RAPYD_WEBHOOK_SECRET
    value: ${RAPYD_WEBHOOK_SECRET}
  - key: RAPYD_MERCHANT_ACCOUNT
    value: ${RAPYD_MERCHANT_ACCOUNT}
  - key: RAPYD_P2P_ENABLED
    value: "true"
  - key: SENDGRID_API_KEY
    value: ${SENDGRID_API_KEY}
  - key: FROM_EMAIL
    value: noreply@zappay.com
  - key: FROM_NAME
    value: ZapPay
  - key: TWILIO_ACCOUNT_SID
    value: ${TWILIO_ACCOUNT_SID}
  - key: TWILIO_AUTH_TOKEN
    value: ${TWILIO_AUTH_TOKEN}
  - key: TWILIO_PHONE_NUMBER
    value: ${TWILIO_PHONE_NUMBER}
  - key: FRONTEND_URL
    value: https://zappay.site
  - key: CORS_ORIGIN
    value: https://zappay.site,https://www.zappay.site
  
  # Database Security Configuration
  - key: DB_CA_CERT
    value: ${DB_CA_CERT}
  - key: DB_CLIENT_CERT
    value: ${DB_CLIENT_CERT}
  - key: DB_CLIENT_KEY
    value: ${DB_CLIENT_KEY}
  
  # Redis Security Configuration
  - key: REDIS_PASSWORD
    value: ${REDIS_PASSWORD}
  - key: REDIS_USERNAME
    value: ${REDIS_USERNAME}
  
  # Security Headers and Rate Limiting
  - key: BCRYPT_ROUNDS
    value: "12"
  - key: RATE_LIMIT_WINDOW_MS
    value: "900000"
  - key: RATE_LIMIT_MAX_REQUESTS
    value: "100"
  
  # Logging and Monitoring
  - key: LOG_LEVEL
    value: "info"
  - key: LOG_FILE
    value: "/var/log/zappay/app.log"

databases:
- name: zappay-postgres
  engine: PG
  version: "14"
  size: db-s-1vcpu-1gb
  num_nodes: 1

- name: zappay-redis
  engine: REDIS
  version: "7"
  size: db-s-1vcpu-1gb
  num_nodes: 1
